name: Python Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ["3.9", "3.11"]


    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test-requirements.txt
    - name: Restore engines
      id: cache-temp-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          TEMP
        key: ${{ matrix.os }}-engines
    - name: Test with pytest
      run: |
        pytest --log-cli-level=10
    - name: Save engines
      id: cache-temp-save
      uses: actions/cache/save@v3
