name: Versioning

on:
  push:
    branches: [ main ]

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  versioning:
    if: github.repository == 'M-DinhHoangViet/Lichess-Bot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML
      - name: Update version
        id: new-version
        run: python .github/workflows/update_version.py
      - name: Auto update version
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "actions-user"
          git add -A .
          git commit -m "Auto update version"
          git push origin HEAD:main
